### ISSUE TITLE
Dyadic EKM Doc Edits

### ISSUE THREAD

**Issue by mjgutermuth** [pivotal-cf/docs-dyadic-service-broker#2]
Hi @AmyDyadic , We've done some tidy-up and formatting on the new Dyadic EKM docs. It looks pretty good, I hope you agree. We do have a few questions for you about the Code Samples. Please, could you write a few lines on what these are for. Who uses them? Do developers paste these into their apps? Does the product only support Java apps? 
Also, could you clarify some terms: What is the "Dyadic EKM provider"? Is that the same as the "EKM Client" mentioned elsewhere? 
Is there Dyadic documentation that we should reference in this tile doc?

**Comment by AmyDyadic** [comment]
Hi @mjgutermuth, I've made some changes in the documentation and have answers to your questions below:
QUESTION:
Please, could you write a few lines on what these are for. 
ANSWER: 
Sure, I did. Please check.

QUESTION:
Who uses them? Do developers paste these into their apps?
ANSWER: 
Yes, they are sample codes for developers to paste into their apps.

QUESTION:
 Does the product only support Java apps?
ANSWER: 
The product supports different platforms not just Java, but with Pivotal we only support Java at the moment, as we have only integrated with the Java buildpack.

QUESTION:
Also, could you clarify some terms: What is the "Dyadic EKM provider"? Is that the same as the "EKM Client" mentioned elsewhere?
ANSWER: 
The Dyadic EKM provider is the "Dyadic EKM java provider" and I've updated the term in the documentation. The Dyadic EKM java provider is a part of the Dyadic EKM client.

QUESTION:
Is there Dyadic documentation that we should reference in this tile doc?
ANSWER: 
At this time, we don't believe there is any need to reference additional documentation.

**Comment by animatedmax** [comment]
Hi @AmyDyadic we updated to docs with the information you provided. Thanks!
